with-expecter: true
inpackage: false
dir: "{{.InterfaceDir}}/mock{{.PackageName}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mock{{.PackageName}}"
filename: "mock_{{.InterfaceName|lower}}.go"
packages:
    github.com/dropwhile/icbt/internal/app/service:
        config:
        interfaces:
            Servicer:
                config:
    github.com/dropwhile/icbt/internal/mail:
        config:
        interfaces:
            MailSender:
                config: