// Code generated by "stringer -type=Job"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[jNotifier-1]
	_ = x[jArchiver-2]
}

const _Job_name = "jNotifierjArchiver"

var _Job_index = [...]uint8{0, 9, 18}

func (i Job) String() string {
	i -= 1
	if i < 0 || i >= Job(len(_Job_index)-1) {
		return "Job(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Job_name[_Job_index[i]:_Job_index[i+1]]
}
