// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: icbt/rpc/v1/constraints.proto

package rpcv1

import (
	validate "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_icbt_rpc_v1_constraints_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*validate.StringRules)(nil),
		ExtensionType: (*bool)(nil),
		Field:         70000001,
		Name:          "icbt.rpc.v1.refid",
		Tag:           "varint,70000001,opt,name=refid",
		Filename:      "icbt/rpc/v1/constraints.proto",
	},
}

// Extension fields to validate.StringRules.
var (
	// optional bool refid = 70000001;
	E_Refid = &file_icbt_rpc_v1_constraints_proto_extTypes[0]
)

var File_icbt_rpc_v1_constraints_proto protoreflect.FileDescriptor

const file_icbt_rpc_v1_constraints_proto_rawDesc = "" +
	"\n" +
	"\x1dicbt/rpc/v1/constraints.proto\x12\vicbt.rpc.v1\x1a\x1bbuf/validate/validate.proto\x1a!google/protobuf/go_features.proto:\x83\x01\n" +
	"\x05refid\x12\x19.buf.validate.StringRules\x18\x81\xbb\xb0! \x01(\bBO\xc2HL\n" +
	"J\n" +
	"\fstring.refid\x12\x17must be in refid format\x1a!this.matches('^[0-9a-zA-Z]{26}$')R\x05refidB\xb5\x01\n" +
	"\x0fcom.icbt.rpc.v1B\x10ConstraintsProtoP\x01Z8github.com/dropwhile/icanbringthat/rpc/icbt/rpc/v1;rpcv1\xa2\x02\x03IRX\xaa\x02\vIcbt.Rpc.V1\xca\x02\vIcbt\\Rpc\\V1\xe2\x02\x17Icbt\\Rpc\\V1\\GPBMetadata\xea\x02\rIcbt::Rpc::V1\x92\x03\a\xd2>\x02\x10\x03\b\x02b\beditionsp\xe8\a"

var file_icbt_rpc_v1_constraints_proto_goTypes = []any{
	(*validate.StringRules)(nil), // 0: buf.validate.StringRules
}
var file_icbt_rpc_v1_constraints_proto_depIdxs = []int32{
	0, // 0: icbt.rpc.v1.refid:extendee -> buf.validate.StringRules
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_icbt_rpc_v1_constraints_proto_init() }
func file_icbt_rpc_v1_constraints_proto_init() {
	if File_icbt_rpc_v1_constraints_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_icbt_rpc_v1_constraints_proto_rawDesc), len(file_icbt_rpc_v1_constraints_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_icbt_rpc_v1_constraints_proto_goTypes,
		DependencyIndexes: file_icbt_rpc_v1_constraints_proto_depIdxs,
		ExtensionInfos:    file_icbt_rpc_v1_constraints_proto_extTypes,
	}.Build()
	File_icbt_rpc_v1_constraints_proto = out.File
	file_icbt_rpc_v1_constraints_proto_goTypes = nil
	file_icbt_rpc_v1_constraints_proto_depIdxs = nil
}
