// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: icbt/rpc/v1/event.proto

package rpcv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId       string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	xxx_hidden_Name        string                 `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_When        *TimestampTZ           `protobuf:"bytes,4,opt,name=when"`
	xxx_hidden_Archived    bool                   `protobuf:"varint,5,opt,name=archived"`
	xxx_hidden_Created     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Event) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Event) GetWhen() *TimestampTZ {
	if x != nil {
		return x.xxx_hidden_When
	}
	return nil
}

func (x *Event) GetArchived() bool {
	if x != nil {
		return x.xxx_hidden_Archived
	}
	return false
}

func (x *Event) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Created
	}
	return nil
}

func (x *Event) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

func (x *Event) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Event) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Event) SetWhen(v *TimestampTZ) {
	x.xxx_hidden_When = v
}

func (x *Event) SetArchived(v bool) {
	x.xxx_hidden_Archived = v
}

func (x *Event) SetCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Created = v
}

func (x *Event) HasWhen() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_When != nil
}

func (x *Event) HasCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Created != nil
}

func (x *Event) ClearWhen() {
	x.xxx_hidden_When = nil
}

func (x *Event) ClearCreated() {
	x.xxx_hidden_Created = nil
}

type Event_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId       string
	Name        string
	Description string
	When        *TimestampTZ
	Archived    bool
	Created     *timestamppb.Timestamp
}

func (b0 Event_builder) Build() *Event {
	m0 := &Event{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_When = b.When
	x.xxx_hidden_Archived = b.Archived
	x.xxx_hidden_Created = b.Created
	return m0
}

type EventItem struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId       string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	xxx_hidden_Description string                 `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Created     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventItem) Reset() {
	*x = EventItem{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventItem) ProtoMessage() {}

func (x *EventItem) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventItem) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventItem) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *EventItem) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Created
	}
	return nil
}

func (x *EventItem) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

func (x *EventItem) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *EventItem) SetCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Created = v
}

func (x *EventItem) HasCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Created != nil
}

func (x *EventItem) ClearCreated() {
	x.xxx_hidden_Created = nil
}

type EventItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId       string
	Description string
	Created     *timestamppb.Timestamp
}

func (b0 EventItem_builder) Build() *EventItem {
	m0 := &EventItem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Created = b.Created
	return m0
}

type EventCreateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Description string                 `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_When        *TimestampTZ           `protobuf:"bytes,3,opt,name=when"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventCreateRequest) Reset() {
	*x = EventCreateRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCreateRequest) ProtoMessage() {}

func (x *EventCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventCreateRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *EventCreateRequest) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *EventCreateRequest) GetWhen() *TimestampTZ {
	if x != nil {
		return x.xxx_hidden_When
	}
	return nil
}

func (x *EventCreateRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *EventCreateRequest) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *EventCreateRequest) SetWhen(v *TimestampTZ) {
	x.xxx_hidden_When = v
}

func (x *EventCreateRequest) HasWhen() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_When != nil
}

func (x *EventCreateRequest) ClearWhen() {
	x.xxx_hidden_When = nil
}

type EventCreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        string
	Description string
	When        *TimestampTZ
}

func (b0 EventCreateRequest_builder) Build() *EventCreateRequest {
	m0 := &EventCreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_When = b.When
	return m0
}

type EventCreateResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Event *Event                 `protobuf:"bytes,1,opt,name=event"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventCreateResponse) Reset() {
	*x = EventCreateResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCreateResponse) ProtoMessage() {}

func (x *EventCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventCreateResponse) GetEvent() *Event {
	if x != nil {
		return x.xxx_hidden_Event
	}
	return nil
}

func (x *EventCreateResponse) SetEvent(v *Event) {
	x.xxx_hidden_Event = v
}

func (x *EventCreateResponse) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Event != nil
}

func (x *EventCreateResponse) ClearEvent() {
	x.xxx_hidden_Event = nil
}

type EventCreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Event *Event
}

func (b0 EventCreateResponse_builder) Build() *EventCreateResponse {
	m0 := &EventCreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Event = b.Event
	return m0
}

type EventDeleteRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventDeleteRequest) Reset() {
	*x = EventDeleteRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDeleteRequest) ProtoMessage() {}

func (x *EventDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventDeleteRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventDeleteRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

type EventDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId string
}

func (b0 EventDeleteRequest_builder) Build() *EventDeleteRequest {
	m0 := &EventDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	return m0
}

type EventUpdateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId       string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Description *string                `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_When        *TimestampTZ           `protobuf:"bytes,4,opt,name=when"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventUpdateRequest) Reset() {
	*x = EventUpdateRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUpdateRequest) ProtoMessage() {}

func (x *EventUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventUpdateRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventUpdateRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *EventUpdateRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *EventUpdateRequest) GetWhen() *TimestampTZ {
	if x != nil {
		return x.xxx_hidden_When
	}
	return nil
}

func (x *EventUpdateRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

func (x *EventUpdateRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *EventUpdateRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *EventUpdateRequest) SetWhen(v *TimestampTZ) {
	x.xxx_hidden_When = v
}

func (x *EventUpdateRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EventUpdateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *EventUpdateRequest) HasWhen() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_When != nil
}

func (x *EventUpdateRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *EventUpdateRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *EventUpdateRequest) ClearWhen() {
	x.xxx_hidden_When = nil
}

type EventUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId       string
	Name        *string
	Description *string
	When        *TimestampTZ
}

func (b0 EventUpdateRequest_builder) Build() *EventUpdateRequest {
	m0 := &EventUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Description = b.Description
	}
	x.xxx_hidden_When = b.When
	return m0
}

type EventGetDetailsRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventGetDetailsRequest) Reset() {
	*x = EventGetDetailsRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventGetDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventGetDetailsRequest) ProtoMessage() {}

func (x *EventGetDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventGetDetailsRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventGetDetailsRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

type EventGetDetailsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId string
}

func (b0 EventGetDetailsRequest_builder) Build() *EventGetDetailsRequest {
	m0 := &EventGetDetailsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	return m0
}

type EventGetDetailsResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Event    *Event                 `protobuf:"bytes,1,opt,name=event"`
	xxx_hidden_Items    *[]*EventItem          `protobuf:"bytes,2,rep,name=items"`
	xxx_hidden_Earmarks *[]*Earmark            `protobuf:"bytes,3,rep,name=earmarks"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventGetDetailsResponse) Reset() {
	*x = EventGetDetailsResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventGetDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventGetDetailsResponse) ProtoMessage() {}

func (x *EventGetDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventGetDetailsResponse) GetEvent() *Event {
	if x != nil {
		return x.xxx_hidden_Event
	}
	return nil
}

func (x *EventGetDetailsResponse) GetItems() []*EventItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *EventGetDetailsResponse) GetEarmarks() []*Earmark {
	if x != nil {
		if x.xxx_hidden_Earmarks != nil {
			return *x.xxx_hidden_Earmarks
		}
	}
	return nil
}

func (x *EventGetDetailsResponse) SetEvent(v *Event) {
	x.xxx_hidden_Event = v
}

func (x *EventGetDetailsResponse) SetItems(v []*EventItem) {
	x.xxx_hidden_Items = &v
}

func (x *EventGetDetailsResponse) SetEarmarks(v []*Earmark) {
	x.xxx_hidden_Earmarks = &v
}

func (x *EventGetDetailsResponse) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Event != nil
}

func (x *EventGetDetailsResponse) ClearEvent() {
	x.xxx_hidden_Event = nil
}

type EventGetDetailsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Event    *Event
	Items    []*EventItem
	Earmarks []*Earmark
}

func (b0 EventGetDetailsResponse_builder) Build() *EventGetDetailsResponse {
	m0 := &EventGetDetailsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Event = b.Event
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_Earmarks = &b.Earmarks
	return m0
}

type EventsListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pagination  *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination"`
	xxx_hidden_Archived    bool                   `protobuf:"varint,2,opt,name=archived"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventsListRequest) Reset() {
	*x = EventsListRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsListRequest) ProtoMessage() {}

func (x *EventsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventsListRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *EventsListRequest) GetArchived() bool {
	if x != nil {
		return x.xxx_hidden_Archived
	}
	return false
}

func (x *EventsListRequest) SetPagination(v *PaginationRequest) {
	x.xxx_hidden_Pagination = v
}

func (x *EventsListRequest) SetArchived(v bool) {
	x.xxx_hidden_Archived = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *EventsListRequest) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *EventsListRequest) HasArchived() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EventsListRequest) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

func (x *EventsListRequest) ClearArchived() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Archived = false
}

type EventsListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Pagination *PaginationRequest
	Archived   *bool
}

func (b0 EventsListRequest_builder) Build() *EventsListRequest {
	m0 := &EventsListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Pagination = b.Pagination
	if b.Archived != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Archived = *b.Archived
	}
	return m0
}

type EventsListResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Events     *[]*Event              `protobuf:"bytes,1,rep,name=events"`
	xxx_hidden_Pagination *PaginationResult      `protobuf:"bytes,2,opt,name=pagination"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EventsListResponse) Reset() {
	*x = EventsListResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsListResponse) ProtoMessage() {}

func (x *EventsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventsListResponse) GetEvents() []*Event {
	if x != nil {
		if x.xxx_hidden_Events != nil {
			return *x.xxx_hidden_Events
		}
	}
	return nil
}

func (x *EventsListResponse) GetPagination() *PaginationResult {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *EventsListResponse) SetEvents(v []*Event) {
	x.xxx_hidden_Events = &v
}

func (x *EventsListResponse) SetPagination(v *PaginationResult) {
	x.xxx_hidden_Pagination = v
}

func (x *EventsListResponse) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *EventsListResponse) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

type EventsListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Events     []*Event
	Pagination *PaginationResult
}

func (b0 EventsListResponse_builder) Build() *EventsListResponse {
	m0 := &EventsListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Events = &b.Events
	x.xxx_hidden_Pagination = b.Pagination
	return m0
}

type EventListItemsRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventListItemsRequest) Reset() {
	*x = EventListItemsRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListItemsRequest) ProtoMessage() {}

func (x *EventListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventListItemsRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventListItemsRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

type EventListItemsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId string
}

func (b0 EventListItemsRequest_builder) Build() *EventListItemsRequest {
	m0 := &EventListItemsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	return m0
}

type EventListItemsResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items      *[]*EventItem          `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Pagination *PaginationResult      `protobuf:"bytes,2,opt,name=pagination"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EventListItemsResponse) Reset() {
	*x = EventListItemsResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListItemsResponse) ProtoMessage() {}

func (x *EventListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventListItemsResponse) GetItems() []*EventItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *EventListItemsResponse) GetPagination() *PaginationResult {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *EventListItemsResponse) SetItems(v []*EventItem) {
	x.xxx_hidden_Items = &v
}

func (x *EventListItemsResponse) SetPagination(v *PaginationResult) {
	x.xxx_hidden_Pagination = v
}

func (x *EventListItemsResponse) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *EventListItemsResponse) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

type EventListItemsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items      []*EventItem
	Pagination *PaginationResult
}

func (b0 EventListItemsResponse_builder) Build() *EventListItemsResponse {
	m0 := &EventListItemsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_Pagination = b.Pagination
	return m0
}

type EventListEarmarksRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventListEarmarksRequest) Reset() {
	*x = EventListEarmarksRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListEarmarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListEarmarksRequest) ProtoMessage() {}

func (x *EventListEarmarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventListEarmarksRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventListEarmarksRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

type EventListEarmarksRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId string
}

func (b0 EventListEarmarksRequest_builder) Build() *EventListEarmarksRequest {
	m0 := &EventListEarmarksRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	return m0
}

type EventListEarmarksResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Earmarks   *[]*Earmark            `protobuf:"bytes,1,rep,name=earmarks"`
	xxx_hidden_Pagination *PaginationResult      `protobuf:"bytes,2,opt,name=pagination"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EventListEarmarksResponse) Reset() {
	*x = EventListEarmarksResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListEarmarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListEarmarksResponse) ProtoMessage() {}

func (x *EventListEarmarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventListEarmarksResponse) GetEarmarks() []*Earmark {
	if x != nil {
		if x.xxx_hidden_Earmarks != nil {
			return *x.xxx_hidden_Earmarks
		}
	}
	return nil
}

func (x *EventListEarmarksResponse) GetPagination() *PaginationResult {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *EventListEarmarksResponse) SetEarmarks(v []*Earmark) {
	x.xxx_hidden_Earmarks = &v
}

func (x *EventListEarmarksResponse) SetPagination(v *PaginationResult) {
	x.xxx_hidden_Pagination = v
}

func (x *EventListEarmarksResponse) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *EventListEarmarksResponse) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

type EventListEarmarksResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Earmarks   []*Earmark
	Pagination *PaginationResult
}

func (b0 EventListEarmarksResponse_builder) Build() *EventListEarmarksResponse {
	m0 := &EventListEarmarksResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Earmarks = &b.Earmarks
	x.xxx_hidden_Pagination = b.Pagination
	return m0
}

type EventAddItemRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventRefId  string                 `protobuf:"bytes,1,opt,name=event_ref_id,json=eventRefId"`
	xxx_hidden_Description string                 `protobuf:"bytes,2,opt,name=description"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventAddItemRequest) Reset() {
	*x = EventAddItemRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAddItemRequest) ProtoMessage() {}

func (x *EventAddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventAddItemRequest) GetEventRefId() string {
	if x != nil {
		return x.xxx_hidden_EventRefId
	}
	return ""
}

func (x *EventAddItemRequest) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *EventAddItemRequest) SetEventRefId(v string) {
	x.xxx_hidden_EventRefId = v
}

func (x *EventAddItemRequest) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

type EventAddItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventRefId  string
	Description string
}

func (b0 EventAddItemRequest_builder) Build() *EventAddItemRequest {
	m0 := &EventAddItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventRefId = b.EventRefId
	x.xxx_hidden_Description = b.Description
	return m0
}

type EventAddItemResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventItem *EventItem             `protobuf:"bytes,1,opt,name=event_item,json=eventItem"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EventAddItemResponse) Reset() {
	*x = EventAddItemResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAddItemResponse) ProtoMessage() {}

func (x *EventAddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventAddItemResponse) GetEventItem() *EventItem {
	if x != nil {
		return x.xxx_hidden_EventItem
	}
	return nil
}

func (x *EventAddItemResponse) SetEventItem(v *EventItem) {
	x.xxx_hidden_EventItem = v
}

func (x *EventAddItemResponse) HasEventItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventItem != nil
}

func (x *EventAddItemResponse) ClearEventItem() {
	x.xxx_hidden_EventItem = nil
}

type EventAddItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventItem *EventItem
}

func (b0 EventAddItemResponse_builder) Build() *EventAddItemResponse {
	m0 := &EventAddItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventItem = b.EventItem
	return m0
}

type EventRemoveItemRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventRemoveItemRequest) Reset() {
	*x = EventRemoveItemRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRemoveItemRequest) ProtoMessage() {}

func (x *EventRemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventRemoveItemRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventRemoveItemRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

type EventRemoveItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId string
}

func (b0 EventRemoveItemRequest_builder) Build() *EventRemoveItemRequest {
	m0 := &EventRemoveItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	return m0
}

type EventUpdateItemRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId       string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	xxx_hidden_Description string                 `protobuf:"bytes,2,opt,name=description"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventUpdateItemRequest) Reset() {
	*x = EventUpdateItemRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventUpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUpdateItemRequest) ProtoMessage() {}

func (x *EventUpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventUpdateItemRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventUpdateItemRequest) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *EventUpdateItemRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

func (x *EventUpdateItemRequest) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

type EventUpdateItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId       string
	Description string
}

func (b0 EventUpdateItemRequest_builder) Build() *EventUpdateItemRequest {
	m0 := &EventUpdateItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	x.xxx_hidden_Description = b.Description
	return m0
}

type EventUpdateItemResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventItem *EventItem             `protobuf:"bytes,1,opt,name=event_item,json=eventItem"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EventUpdateItemResponse) Reset() {
	*x = EventUpdateItemResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventUpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUpdateItemResponse) ProtoMessage() {}

func (x *EventUpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventUpdateItemResponse) GetEventItem() *EventItem {
	if x != nil {
		return x.xxx_hidden_EventItem
	}
	return nil
}

func (x *EventUpdateItemResponse) SetEventItem(v *EventItem) {
	x.xxx_hidden_EventItem = v
}

func (x *EventUpdateItemResponse) HasEventItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventItem != nil
}

func (x *EventUpdateItemResponse) ClearEventItem() {
	x.xxx_hidden_EventItem = nil
}

type EventUpdateItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventItem *EventItem
}

func (b0 EventUpdateItemResponse_builder) Build() *EventUpdateItemResponse {
	m0 := &EventUpdateItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventItem = b.EventItem
	return m0
}

var File_icbt_rpc_v1_event_proto protoreflect.FileDescriptor

const file_icbt_rpc_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x17icbt/rpc/v1/event.proto\x12\vicbt.rpc.v1\x1a\x1bbuf/validate/validate.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dicbt/rpc/v1/constraints.proto\x1a\x19icbt/rpc/v1/earmark.proto\x1a\x1cicbt/rpc/v1/pagination.proto\x1a\x1dicbt/rpc/v1/timestamptz.proto\"\xd4\x01\n" +
	"\x05Event\x12\x15\n" +
	"\x06ref_id\x18\x01 \x01(\tR\x05refId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12,\n" +
	"\x04when\x18\x04 \x01(\v2\x18.icbt.rpc.v1.TimestampTZR\x04when\x12\x1a\n" +
	"\barchived\x18\x05 \x01(\bR\barchived\x124\n" +
	"\acreated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\"z\n" +
	"\tEventItem\x12\x15\n" +
	"\x06ref_id\x18\x01 \x01(\tR\x05refId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\"\x8a\x01\n" +
	"\x12EventCreateRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdescription\x12,\n" +
	"\x04when\x18\x03 \x01(\v2\x18.icbt.rpc.v1.TimestampTZR\x04when\"?\n" +
	"\x13EventCreateResponse\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.icbt.rpc.v1.EventR\x05event\"8\n" +
	"\x12EventDeleteRequest\x12\"\n" +
	"\x06ref_id\x18\x01 \x01(\tB\v\xbaH\br\x06\x88\u0603\x8b\x02\x01R\x05refId\"\xb1\x01\n" +
	"\x12EventUpdateRequest\x12\"\n" +
	"\x06ref_id\x18\x01 \x01(\tB\v\xbaH\br\x06\x88\u0603\x8b\x02\x01R\x05refId\x12\x19\n" +
	"\x04name\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x01R\x04name\x12'\n" +
	"\vdescription\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x01R\vdescription\x123\n" +
	"\x04when\x18\x04 \x01(\v2\x18.icbt.rpc.v1.TimestampTZB\x05\xaa\x01\x02\b\x01R\x04when\"<\n" +
	"\x16EventGetDetailsRequest\x12\"\n" +
	"\x06ref_id\x18\x01 \x01(\tB\v\xbaH\br\x06\x88\u0603\x8b\x02\x01R\x05refId\"\xa3\x01\n" +
	"\x17EventGetDetailsResponse\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.icbt.rpc.v1.EventR\x05event\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.icbt.rpc.v1.EventItemR\x05items\x120\n" +
	"\bearmarks\x18\x03 \x03(\v2\x14.icbt.rpc.v1.EarmarkR\bearmarks\"}\n" +
	"\x11EventsListRequest\x12E\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1e.icbt.rpc.v1.PaginationRequestB\x05\xaa\x01\x02\b\x01R\n" +
	"pagination\x12!\n" +
	"\barchived\x18\x02 \x01(\bB\x05\xaa\x01\x02\b\x01R\barchived\"\x86\x01\n" +
	"\x12EventsListResponse\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.icbt.rpc.v1.EventR\x06events\x12D\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.icbt.rpc.v1.PaginationResultB\x05\xaa\x01\x02\b\x01R\n" +
	"pagination\";\n" +
	"\x15EventListItemsRequest\x12\"\n" +
	"\x06ref_id\x18\x01 \x01(\tB\v\xbaH\br\x06\x88\u0603\x8b\x02\x01R\x05refId\"\x8c\x01\n" +
	"\x16EventListItemsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.icbt.rpc.v1.EventItemR\x05items\x12D\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.icbt.rpc.v1.PaginationResultB\x05\xaa\x01\x02\b\x01R\n" +
	"pagination\">\n" +
	"\x18EventListEarmarksRequest\x12\"\n" +
	"\x06ref_id\x18\x01 \x01(\tB\v\xbaH\br\x06\x88\u0603\x8b\x02\x01R\x05refId\"\x93\x01\n" +
	"\x19EventListEarmarksResponse\x120\n" +
	"\bearmarks\x18\x01 \x03(\v2\x14.icbt.rpc.v1.EarmarkR\bearmarks\x12D\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.icbt.rpc.v1.PaginationResultB\x05\xaa\x01\x02\b\x01R\n" +
	"pagination\"f\n" +
	"\x13EventAddItemRequest\x12-\n" +
	"\fevent_ref_id\x18\x01 \x01(\tB\v\xbaH\br\x06\x88\u0603\x8b\x02\x01R\n" +
	"eventRefId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"M\n" +
	"\x14EventAddItemResponse\x125\n" +
	"\n" +
	"event_item\x18\x01 \x01(\v2\x16.icbt.rpc.v1.EventItemR\teventItem\"<\n" +
	"\x16EventRemoveItemRequest\x12\"\n" +
	"\x06ref_id\x18\x01 \x01(\tB\v\xbaH\br\x06\x88\u0603\x8b\x02\x01R\x05refId\"^\n" +
	"\x16EventUpdateItemRequest\x12\"\n" +
	"\x06ref_id\x18\x01 \x01(\tB\v\xbaH\br\x06\x88\u0603\x8b\x02\x01R\x05refId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"P\n" +
	"\x17EventUpdateItemResponse\x125\n" +
	"\n" +
	"event_item\x18\x01 \x01(\v2\x16.icbt.rpc.v1.EventItemR\teventItemB\xaf\x01\n" +
	"\x0fcom.icbt.rpc.v1B\n" +
	"EventProtoP\x01Z8github.com/dropwhile/icanbringthat/rpc/icbt/rpc/v1;rpcv1\xa2\x02\x03IRX\xaa\x02\vIcbt.Rpc.V1\xca\x02\vIcbt\\Rpc\\V1\xe2\x02\x17Icbt\\Rpc\\V1\\GPBMetadata\xea\x02\rIcbt::Rpc::V1\x92\x03\a\xd2>\x02\x10\x03\b\x02b\beditionsp\xe8\a"

var file_icbt_rpc_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_icbt_rpc_v1_event_proto_goTypes = []any{
	(*Event)(nil),                     // 0: icbt.rpc.v1.Event
	(*EventItem)(nil),                 // 1: icbt.rpc.v1.EventItem
	(*EventCreateRequest)(nil),        // 2: icbt.rpc.v1.EventCreateRequest
	(*EventCreateResponse)(nil),       // 3: icbt.rpc.v1.EventCreateResponse
	(*EventDeleteRequest)(nil),        // 4: icbt.rpc.v1.EventDeleteRequest
	(*EventUpdateRequest)(nil),        // 5: icbt.rpc.v1.EventUpdateRequest
	(*EventGetDetailsRequest)(nil),    // 6: icbt.rpc.v1.EventGetDetailsRequest
	(*EventGetDetailsResponse)(nil),   // 7: icbt.rpc.v1.EventGetDetailsResponse
	(*EventsListRequest)(nil),         // 8: icbt.rpc.v1.EventsListRequest
	(*EventsListResponse)(nil),        // 9: icbt.rpc.v1.EventsListResponse
	(*EventListItemsRequest)(nil),     // 10: icbt.rpc.v1.EventListItemsRequest
	(*EventListItemsResponse)(nil),    // 11: icbt.rpc.v1.EventListItemsResponse
	(*EventListEarmarksRequest)(nil),  // 12: icbt.rpc.v1.EventListEarmarksRequest
	(*EventListEarmarksResponse)(nil), // 13: icbt.rpc.v1.EventListEarmarksResponse
	(*EventAddItemRequest)(nil),       // 14: icbt.rpc.v1.EventAddItemRequest
	(*EventAddItemResponse)(nil),      // 15: icbt.rpc.v1.EventAddItemResponse
	(*EventRemoveItemRequest)(nil),    // 16: icbt.rpc.v1.EventRemoveItemRequest
	(*EventUpdateItemRequest)(nil),    // 17: icbt.rpc.v1.EventUpdateItemRequest
	(*EventUpdateItemResponse)(nil),   // 18: icbt.rpc.v1.EventUpdateItemResponse
	(*TimestampTZ)(nil),               // 19: icbt.rpc.v1.TimestampTZ
	(*timestamppb.Timestamp)(nil),     // 20: google.protobuf.Timestamp
	(*Earmark)(nil),                   // 21: icbt.rpc.v1.Earmark
	(*PaginationRequest)(nil),         // 22: icbt.rpc.v1.PaginationRequest
	(*PaginationResult)(nil),          // 23: icbt.rpc.v1.PaginationResult
}
var file_icbt_rpc_v1_event_proto_depIdxs = []int32{
	19, // 0: icbt.rpc.v1.Event.when:type_name -> icbt.rpc.v1.TimestampTZ
	20, // 1: icbt.rpc.v1.Event.created:type_name -> google.protobuf.Timestamp
	20, // 2: icbt.rpc.v1.EventItem.created:type_name -> google.protobuf.Timestamp
	19, // 3: icbt.rpc.v1.EventCreateRequest.when:type_name -> icbt.rpc.v1.TimestampTZ
	0,  // 4: icbt.rpc.v1.EventCreateResponse.event:type_name -> icbt.rpc.v1.Event
	19, // 5: icbt.rpc.v1.EventUpdateRequest.when:type_name -> icbt.rpc.v1.TimestampTZ
	0,  // 6: icbt.rpc.v1.EventGetDetailsResponse.event:type_name -> icbt.rpc.v1.Event
	1,  // 7: icbt.rpc.v1.EventGetDetailsResponse.items:type_name -> icbt.rpc.v1.EventItem
	21, // 8: icbt.rpc.v1.EventGetDetailsResponse.earmarks:type_name -> icbt.rpc.v1.Earmark
	22, // 9: icbt.rpc.v1.EventsListRequest.pagination:type_name -> icbt.rpc.v1.PaginationRequest
	0,  // 10: icbt.rpc.v1.EventsListResponse.events:type_name -> icbt.rpc.v1.Event
	23, // 11: icbt.rpc.v1.EventsListResponse.pagination:type_name -> icbt.rpc.v1.PaginationResult
	1,  // 12: icbt.rpc.v1.EventListItemsResponse.items:type_name -> icbt.rpc.v1.EventItem
	23, // 13: icbt.rpc.v1.EventListItemsResponse.pagination:type_name -> icbt.rpc.v1.PaginationResult
	21, // 14: icbt.rpc.v1.EventListEarmarksResponse.earmarks:type_name -> icbt.rpc.v1.Earmark
	23, // 15: icbt.rpc.v1.EventListEarmarksResponse.pagination:type_name -> icbt.rpc.v1.PaginationResult
	1,  // 16: icbt.rpc.v1.EventAddItemResponse.event_item:type_name -> icbt.rpc.v1.EventItem
	1,  // 17: icbt.rpc.v1.EventUpdateItemResponse.event_item:type_name -> icbt.rpc.v1.EventItem
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_icbt_rpc_v1_event_proto_init() }
func file_icbt_rpc_v1_event_proto_init() {
	if File_icbt_rpc_v1_event_proto != nil {
		return
	}
	file_icbt_rpc_v1_constraints_proto_init()
	file_icbt_rpc_v1_earmark_proto_init()
	file_icbt_rpc_v1_pagination_proto_init()
	file_icbt_rpc_v1_timestamptz_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_icbt_rpc_v1_event_proto_rawDesc), len(file_icbt_rpc_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_icbt_rpc_v1_event_proto_goTypes,
		DependencyIndexes: file_icbt_rpc_v1_event_proto_depIdxs,
		MessageInfos:      file_icbt_rpc_v1_event_proto_msgTypes,
	}.Build()
	File_icbt_rpc_v1_event_proto = out.File
	file_icbt_rpc_v1_event_proto_goTypes = nil
	file_icbt_rpc_v1_event_proto_depIdxs = nil
}
