// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: icbt/rpc/v1/event.proto

package rpcv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId       string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	xxx_hidden_Name        string                 `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_When        *TimestampTZ           `protobuf:"bytes,4,opt,name=when"`
	xxx_hidden_Archived    bool                   `protobuf:"varint,5,opt,name=archived"`
	xxx_hidden_Created     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Event) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Event) GetWhen() *TimestampTZ {
	if x != nil {
		return x.xxx_hidden_When
	}
	return nil
}

func (x *Event) GetArchived() bool {
	if x != nil {
		return x.xxx_hidden_Archived
	}
	return false
}

func (x *Event) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Created
	}
	return nil
}

func (x *Event) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

func (x *Event) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Event) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Event) SetWhen(v *TimestampTZ) {
	x.xxx_hidden_When = v
}

func (x *Event) SetArchived(v bool) {
	x.xxx_hidden_Archived = v
}

func (x *Event) SetCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Created = v
}

func (x *Event) HasWhen() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_When != nil
}

func (x *Event) HasCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Created != nil
}

func (x *Event) ClearWhen() {
	x.xxx_hidden_When = nil
}

func (x *Event) ClearCreated() {
	x.xxx_hidden_Created = nil
}

type Event_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId       string
	Name        string
	Description string
	When        *TimestampTZ
	Archived    bool
	Created     *timestamppb.Timestamp
}

func (b0 Event_builder) Build() *Event {
	m0 := &Event{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_When = b.When
	x.xxx_hidden_Archived = b.Archived
	x.xxx_hidden_Created = b.Created
	return m0
}

type EventItem struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId       string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	xxx_hidden_Description string                 `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Created     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventItem) Reset() {
	*x = EventItem{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventItem) ProtoMessage() {}

func (x *EventItem) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventItem) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventItem) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *EventItem) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Created
	}
	return nil
}

func (x *EventItem) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

func (x *EventItem) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *EventItem) SetCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Created = v
}

func (x *EventItem) HasCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Created != nil
}

func (x *EventItem) ClearCreated() {
	x.xxx_hidden_Created = nil
}

type EventItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId       string
	Description string
	Created     *timestamppb.Timestamp
}

func (b0 EventItem_builder) Build() *EventItem {
	m0 := &EventItem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Created = b.Created
	return m0
}

type EventCreateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Description string                 `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_When        *TimestampTZ           `protobuf:"bytes,3,opt,name=when"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventCreateRequest) Reset() {
	*x = EventCreateRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCreateRequest) ProtoMessage() {}

func (x *EventCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventCreateRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *EventCreateRequest) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *EventCreateRequest) GetWhen() *TimestampTZ {
	if x != nil {
		return x.xxx_hidden_When
	}
	return nil
}

func (x *EventCreateRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *EventCreateRequest) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *EventCreateRequest) SetWhen(v *TimestampTZ) {
	x.xxx_hidden_When = v
}

func (x *EventCreateRequest) HasWhen() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_When != nil
}

func (x *EventCreateRequest) ClearWhen() {
	x.xxx_hidden_When = nil
}

type EventCreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        string
	Description string
	When        *TimestampTZ
}

func (b0 EventCreateRequest_builder) Build() *EventCreateRequest {
	m0 := &EventCreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_When = b.When
	return m0
}

type EventCreateResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Event *Event                 `protobuf:"bytes,1,opt,name=event"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventCreateResponse) Reset() {
	*x = EventCreateResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCreateResponse) ProtoMessage() {}

func (x *EventCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventCreateResponse) GetEvent() *Event {
	if x != nil {
		return x.xxx_hidden_Event
	}
	return nil
}

func (x *EventCreateResponse) SetEvent(v *Event) {
	x.xxx_hidden_Event = v
}

func (x *EventCreateResponse) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Event != nil
}

func (x *EventCreateResponse) ClearEvent() {
	x.xxx_hidden_Event = nil
}

type EventCreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Event *Event
}

func (b0 EventCreateResponse_builder) Build() *EventCreateResponse {
	m0 := &EventCreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Event = b.Event
	return m0
}

type EventDeleteRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventDeleteRequest) Reset() {
	*x = EventDeleteRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDeleteRequest) ProtoMessage() {}

func (x *EventDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventDeleteRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventDeleteRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

type EventDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId string
}

func (b0 EventDeleteRequest_builder) Build() *EventDeleteRequest {
	m0 := &EventDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	return m0
}

type EventUpdateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId       string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Description *string                `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_When        *TimestampTZ           `protobuf:"bytes,4,opt,name=when"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventUpdateRequest) Reset() {
	*x = EventUpdateRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUpdateRequest) ProtoMessage() {}

func (x *EventUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventUpdateRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventUpdateRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *EventUpdateRequest) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *EventUpdateRequest) GetWhen() *TimestampTZ {
	if x != nil {
		return x.xxx_hidden_When
	}
	return nil
}

func (x *EventUpdateRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

func (x *EventUpdateRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *EventUpdateRequest) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *EventUpdateRequest) SetWhen(v *TimestampTZ) {
	x.xxx_hidden_When = v
}

func (x *EventUpdateRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EventUpdateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *EventUpdateRequest) HasWhen() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_When != nil
}

func (x *EventUpdateRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *EventUpdateRequest) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *EventUpdateRequest) ClearWhen() {
	x.xxx_hidden_When = nil
}

type EventUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId       string
	Name        *string
	Description *string
	When        *TimestampTZ
}

func (b0 EventUpdateRequest_builder) Build() *EventUpdateRequest {
	m0 := &EventUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Description = b.Description
	}
	x.xxx_hidden_When = b.When
	return m0
}

type EventGetDetailsRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventGetDetailsRequest) Reset() {
	*x = EventGetDetailsRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventGetDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventGetDetailsRequest) ProtoMessage() {}

func (x *EventGetDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventGetDetailsRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventGetDetailsRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

type EventGetDetailsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId string
}

func (b0 EventGetDetailsRequest_builder) Build() *EventGetDetailsRequest {
	m0 := &EventGetDetailsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	return m0
}

type EventGetDetailsResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Event    *Event                 `protobuf:"bytes,1,opt,name=event"`
	xxx_hidden_Items    *[]*EventItem          `protobuf:"bytes,2,rep,name=items"`
	xxx_hidden_Earmarks *[]*Earmark            `protobuf:"bytes,3,rep,name=earmarks"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventGetDetailsResponse) Reset() {
	*x = EventGetDetailsResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventGetDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventGetDetailsResponse) ProtoMessage() {}

func (x *EventGetDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventGetDetailsResponse) GetEvent() *Event {
	if x != nil {
		return x.xxx_hidden_Event
	}
	return nil
}

func (x *EventGetDetailsResponse) GetItems() []*EventItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *EventGetDetailsResponse) GetEarmarks() []*Earmark {
	if x != nil {
		if x.xxx_hidden_Earmarks != nil {
			return *x.xxx_hidden_Earmarks
		}
	}
	return nil
}

func (x *EventGetDetailsResponse) SetEvent(v *Event) {
	x.xxx_hidden_Event = v
}

func (x *EventGetDetailsResponse) SetItems(v []*EventItem) {
	x.xxx_hidden_Items = &v
}

func (x *EventGetDetailsResponse) SetEarmarks(v []*Earmark) {
	x.xxx_hidden_Earmarks = &v
}

func (x *EventGetDetailsResponse) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Event != nil
}

func (x *EventGetDetailsResponse) ClearEvent() {
	x.xxx_hidden_Event = nil
}

type EventGetDetailsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Event    *Event
	Items    []*EventItem
	Earmarks []*Earmark
}

func (b0 EventGetDetailsResponse_builder) Build() *EventGetDetailsResponse {
	m0 := &EventGetDetailsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Event = b.Event
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_Earmarks = &b.Earmarks
	return m0
}

type EventsListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pagination  *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination"`
	xxx_hidden_Archived    bool                   `protobuf:"varint,2,opt,name=archived"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventsListRequest) Reset() {
	*x = EventsListRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsListRequest) ProtoMessage() {}

func (x *EventsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventsListRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *EventsListRequest) GetArchived() bool {
	if x != nil {
		return x.xxx_hidden_Archived
	}
	return false
}

func (x *EventsListRequest) SetPagination(v *PaginationRequest) {
	x.xxx_hidden_Pagination = v
}

func (x *EventsListRequest) SetArchived(v bool) {
	x.xxx_hidden_Archived = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *EventsListRequest) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *EventsListRequest) HasArchived() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EventsListRequest) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

func (x *EventsListRequest) ClearArchived() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Archived = false
}

type EventsListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Pagination *PaginationRequest
	Archived   *bool
}

func (b0 EventsListRequest_builder) Build() *EventsListRequest {
	m0 := &EventsListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Pagination = b.Pagination
	if b.Archived != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Archived = *b.Archived
	}
	return m0
}

type EventsListResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Events     *[]*Event              `protobuf:"bytes,1,rep,name=events"`
	xxx_hidden_Pagination *PaginationResult      `protobuf:"bytes,2,opt,name=pagination"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EventsListResponse) Reset() {
	*x = EventsListResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsListResponse) ProtoMessage() {}

func (x *EventsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventsListResponse) GetEvents() []*Event {
	if x != nil {
		if x.xxx_hidden_Events != nil {
			return *x.xxx_hidden_Events
		}
	}
	return nil
}

func (x *EventsListResponse) GetPagination() *PaginationResult {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *EventsListResponse) SetEvents(v []*Event) {
	x.xxx_hidden_Events = &v
}

func (x *EventsListResponse) SetPagination(v *PaginationResult) {
	x.xxx_hidden_Pagination = v
}

func (x *EventsListResponse) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *EventsListResponse) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

type EventsListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Events     []*Event
	Pagination *PaginationResult
}

func (b0 EventsListResponse_builder) Build() *EventsListResponse {
	m0 := &EventsListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Events = &b.Events
	x.xxx_hidden_Pagination = b.Pagination
	return m0
}

type EventListItemsRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventListItemsRequest) Reset() {
	*x = EventListItemsRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListItemsRequest) ProtoMessage() {}

func (x *EventListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventListItemsRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventListItemsRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

type EventListItemsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId string
}

func (b0 EventListItemsRequest_builder) Build() *EventListItemsRequest {
	m0 := &EventListItemsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	return m0
}

type EventListItemsResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items      *[]*EventItem          `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Pagination *PaginationResult      `protobuf:"bytes,2,opt,name=pagination"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EventListItemsResponse) Reset() {
	*x = EventListItemsResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListItemsResponse) ProtoMessage() {}

func (x *EventListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventListItemsResponse) GetItems() []*EventItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *EventListItemsResponse) GetPagination() *PaginationResult {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *EventListItemsResponse) SetItems(v []*EventItem) {
	x.xxx_hidden_Items = &v
}

func (x *EventListItemsResponse) SetPagination(v *PaginationResult) {
	x.xxx_hidden_Pagination = v
}

func (x *EventListItemsResponse) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *EventListItemsResponse) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

type EventListItemsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items      []*EventItem
	Pagination *PaginationResult
}

func (b0 EventListItemsResponse_builder) Build() *EventListItemsResponse {
	m0 := &EventListItemsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_Pagination = b.Pagination
	return m0
}

type EventListEarmarksRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventListEarmarksRequest) Reset() {
	*x = EventListEarmarksRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListEarmarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListEarmarksRequest) ProtoMessage() {}

func (x *EventListEarmarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventListEarmarksRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventListEarmarksRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

type EventListEarmarksRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId string
}

func (b0 EventListEarmarksRequest_builder) Build() *EventListEarmarksRequest {
	m0 := &EventListEarmarksRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	return m0
}

type EventListEarmarksResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Earmarks   *[]*Earmark            `protobuf:"bytes,1,rep,name=earmarks"`
	xxx_hidden_Pagination *PaginationResult      `protobuf:"bytes,2,opt,name=pagination"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EventListEarmarksResponse) Reset() {
	*x = EventListEarmarksResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListEarmarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListEarmarksResponse) ProtoMessage() {}

func (x *EventListEarmarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventListEarmarksResponse) GetEarmarks() []*Earmark {
	if x != nil {
		if x.xxx_hidden_Earmarks != nil {
			return *x.xxx_hidden_Earmarks
		}
	}
	return nil
}

func (x *EventListEarmarksResponse) GetPagination() *PaginationResult {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *EventListEarmarksResponse) SetEarmarks(v []*Earmark) {
	x.xxx_hidden_Earmarks = &v
}

func (x *EventListEarmarksResponse) SetPagination(v *PaginationResult) {
	x.xxx_hidden_Pagination = v
}

func (x *EventListEarmarksResponse) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *EventListEarmarksResponse) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

type EventListEarmarksResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Earmarks   []*Earmark
	Pagination *PaginationResult
}

func (b0 EventListEarmarksResponse_builder) Build() *EventListEarmarksResponse {
	m0 := &EventListEarmarksResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Earmarks = &b.Earmarks
	x.xxx_hidden_Pagination = b.Pagination
	return m0
}

type EventAddItemRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventRefId  string                 `protobuf:"bytes,1,opt,name=event_ref_id,json=eventRefId"`
	xxx_hidden_Description string                 `protobuf:"bytes,2,opt,name=description"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventAddItemRequest) Reset() {
	*x = EventAddItemRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAddItemRequest) ProtoMessage() {}

func (x *EventAddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventAddItemRequest) GetEventRefId() string {
	if x != nil {
		return x.xxx_hidden_EventRefId
	}
	return ""
}

func (x *EventAddItemRequest) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *EventAddItemRequest) SetEventRefId(v string) {
	x.xxx_hidden_EventRefId = v
}

func (x *EventAddItemRequest) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

type EventAddItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventRefId  string
	Description string
}

func (b0 EventAddItemRequest_builder) Build() *EventAddItemRequest {
	m0 := &EventAddItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventRefId = b.EventRefId
	x.xxx_hidden_Description = b.Description
	return m0
}

type EventAddItemResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventItem *EventItem             `protobuf:"bytes,1,opt,name=event_item,json=eventItem"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EventAddItemResponse) Reset() {
	*x = EventAddItemResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAddItemResponse) ProtoMessage() {}

func (x *EventAddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventAddItemResponse) GetEventItem() *EventItem {
	if x != nil {
		return x.xxx_hidden_EventItem
	}
	return nil
}

func (x *EventAddItemResponse) SetEventItem(v *EventItem) {
	x.xxx_hidden_EventItem = v
}

func (x *EventAddItemResponse) HasEventItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventItem != nil
}

func (x *EventAddItemResponse) ClearEventItem() {
	x.xxx_hidden_EventItem = nil
}

type EventAddItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventItem *EventItem
}

func (b0 EventAddItemResponse_builder) Build() *EventAddItemResponse {
	m0 := &EventAddItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventItem = b.EventItem
	return m0
}

type EventRemoveItemRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventRemoveItemRequest) Reset() {
	*x = EventRemoveItemRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRemoveItemRequest) ProtoMessage() {}

func (x *EventRemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventRemoveItemRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventRemoveItemRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

type EventRemoveItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId string
}

func (b0 EventRemoveItemRequest_builder) Build() *EventRemoveItemRequest {
	m0 := &EventRemoveItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	return m0
}

type EventUpdateItemRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RefId       string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId"`
	xxx_hidden_Description string                 `protobuf:"bytes,2,opt,name=description"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventUpdateItemRequest) Reset() {
	*x = EventUpdateItemRequest{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventUpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUpdateItemRequest) ProtoMessage() {}

func (x *EventUpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventUpdateItemRequest) GetRefId() string {
	if x != nil {
		return x.xxx_hidden_RefId
	}
	return ""
}

func (x *EventUpdateItemRequest) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *EventUpdateItemRequest) SetRefId(v string) {
	x.xxx_hidden_RefId = v
}

func (x *EventUpdateItemRequest) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

type EventUpdateItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RefId       string
	Description string
}

func (b0 EventUpdateItemRequest_builder) Build() *EventUpdateItemRequest {
	m0 := &EventUpdateItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RefId = b.RefId
	x.xxx_hidden_Description = b.Description
	return m0
}

type EventUpdateItemResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventItem *EventItem             `protobuf:"bytes,1,opt,name=event_item,json=eventItem"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EventUpdateItemResponse) Reset() {
	*x = EventUpdateItemResponse{}
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventUpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUpdateItemResponse) ProtoMessage() {}

func (x *EventUpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icbt_rpc_v1_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventUpdateItemResponse) GetEventItem() *EventItem {
	if x != nil {
		return x.xxx_hidden_EventItem
	}
	return nil
}

func (x *EventUpdateItemResponse) SetEventItem(v *EventItem) {
	x.xxx_hidden_EventItem = v
}

func (x *EventUpdateItemResponse) HasEventItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventItem != nil
}

func (x *EventUpdateItemResponse) ClearEventItem() {
	x.xxx_hidden_EventItem = nil
}

type EventUpdateItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventItem *EventItem
}

func (b0 EventUpdateItemResponse_builder) Build() *EventUpdateItemResponse {
	m0 := &EventUpdateItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventItem = b.EventItem
	return m0
}

var File_icbt_rpc_v1_event_proto protoreflect.FileDescriptor

var file_icbt_rpc_v1_event_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x69, 0x63, 0x62, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x63, 0x62, 0x74, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x69, 0x63, 0x62, 0x74, 0x2f, 0x72, 0x70,
	0x63, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x69, 0x63, 0x62, 0x74, 0x2f, 0x72, 0x70, 0x63,
	0x2f, 0x76, 0x31, 0x2f, 0x65, 0x61, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x69, 0x63, 0x62, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1d, 0x69, 0x63, 0x62, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x74, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd4,
	0x01, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x54, 0x5a, 0x52, 0x04, 0x77,
	0x68, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x12,
	0x34, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x7a, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x22, 0x8a, 0x01, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xba, 0x48, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xba, 0x48, 0x04, 0x72,
	0x02, 0x10, 0x01, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2c, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x54, 0x5a, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x22, 0x3f,
	0x0a, 0x13, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0x38, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0b, 0xba, 0x48, 0x08, 0x72, 0x06, 0x88, 0xd8, 0x83, 0x8b,
	0x02, 0x01, 0x52, 0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x12, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0b, 0xba, 0x48, 0x08, 0x72, 0x06, 0x88, 0xd8, 0x83, 0x8b, 0x02, 0x01, 0x52, 0x05, 0x72,
	0x65, 0x66, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x27, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x54, 0x5a,
	0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x22, 0x3c, 0x0a,
	0x16, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0b, 0xba, 0x48, 0x08, 0x72, 0x06, 0x88, 0xd8,
	0x83, 0x8b, 0x02, 0x01, 0x52, 0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x17,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x30, 0x0a, 0x08, 0x65, 0x61, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x61, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x08, 0x65, 0x61, 0x72, 0x6d, 0x61, 0x72, 0x6b,
	0x73, 0x22, 0x7d, 0x0a, 0x11, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x63, 0x62,
	0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08,
	0x01, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a,
	0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x42,
	0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x08, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64,
	0x22, 0x86, 0x01, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x44, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x0a, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x15, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x0b, 0xba, 0x48, 0x08, 0x72, 0x06, 0x88, 0xd8, 0x83, 0x8b, 0x02, 0x01, 0x52,
	0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x16, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x44, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x18, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x61, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x0b, 0xba, 0x48, 0x08, 0x72, 0x06, 0x88, 0xd8, 0x83, 0x8b, 0x02, 0x01, 0x52, 0x05,
	0x72, 0x65, 0x66, 0x49, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x19, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x61, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x65, 0x61, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x61, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x08, 0x65, 0x61, 0x72,
	0x6d, 0x61, 0x72, 0x6b, 0x73, 0x12, 0x44, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x63, 0x62, 0x74,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52,
	0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x66, 0x0a, 0x13, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2d, 0x0a, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x66, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0b, 0xba, 0x48, 0x08, 0x72, 0x06, 0x88,
	0xd8, 0x83, 0x8b, 0x02, 0x01, 0x52, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x14, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x22, 0x3c, 0x0a, 0x16, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06,
	0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0b, 0xba, 0x48,
	0x08, 0x72, 0x06, 0x88, 0xd8, 0x83, 0x8b, 0x02, 0x01, 0x52, 0x05, 0x72, 0x65, 0x66, 0x49, 0x64,
	0x22, 0x5e, 0x0a, 0x16, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65,
	0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0b, 0xba, 0x48, 0x08, 0x72,
	0x06, 0x88, 0xd8, 0x83, 0x8b, 0x02, 0x01, 0x52, 0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x50, 0x0a, 0x17, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x42, 0xaf, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x63, 0x62, 0x74, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x72, 0x6f, 0x70, 0x77, 0x68, 0x69, 0x6c, 0x65, 0x2f, 0x69, 0x63, 0x61, 0x6e, 0x62,
	0x72, 0x69, 0x6e, 0x67, 0x74, 0x68, 0x61, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x63, 0x62,
	0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x70, 0x63, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x49, 0x52, 0x58, 0xaa, 0x02, 0x0b, 0x49, 0x63, 0x62, 0x74, 0x2e, 0x52, 0x70, 0x63, 0x2e,
	0x56, 0x31, 0xca, 0x02, 0x0b, 0x49, 0x63, 0x62, 0x74, 0x5c, 0x52, 0x70, 0x63, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x17, 0x49, 0x63, 0x62, 0x74, 0x5c, 0x52, 0x70, 0x63, 0x5c, 0x56, 0x31, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0d, 0x49, 0x63, 0x62,
	0x74, 0x3a, 0x3a, 0x52, 0x70, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x92, 0x03, 0x07, 0xd2, 0x3e, 0x02,
	0x10, 0x03, 0x08, 0x02, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8,
	0x07,
})

var file_icbt_rpc_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_icbt_rpc_v1_event_proto_goTypes = []any{
	(*Event)(nil),                     // 0: icbt.rpc.v1.Event
	(*EventItem)(nil),                 // 1: icbt.rpc.v1.EventItem
	(*EventCreateRequest)(nil),        // 2: icbt.rpc.v1.EventCreateRequest
	(*EventCreateResponse)(nil),       // 3: icbt.rpc.v1.EventCreateResponse
	(*EventDeleteRequest)(nil),        // 4: icbt.rpc.v1.EventDeleteRequest
	(*EventUpdateRequest)(nil),        // 5: icbt.rpc.v1.EventUpdateRequest
	(*EventGetDetailsRequest)(nil),    // 6: icbt.rpc.v1.EventGetDetailsRequest
	(*EventGetDetailsResponse)(nil),   // 7: icbt.rpc.v1.EventGetDetailsResponse
	(*EventsListRequest)(nil),         // 8: icbt.rpc.v1.EventsListRequest
	(*EventsListResponse)(nil),        // 9: icbt.rpc.v1.EventsListResponse
	(*EventListItemsRequest)(nil),     // 10: icbt.rpc.v1.EventListItemsRequest
	(*EventListItemsResponse)(nil),    // 11: icbt.rpc.v1.EventListItemsResponse
	(*EventListEarmarksRequest)(nil),  // 12: icbt.rpc.v1.EventListEarmarksRequest
	(*EventListEarmarksResponse)(nil), // 13: icbt.rpc.v1.EventListEarmarksResponse
	(*EventAddItemRequest)(nil),       // 14: icbt.rpc.v1.EventAddItemRequest
	(*EventAddItemResponse)(nil),      // 15: icbt.rpc.v1.EventAddItemResponse
	(*EventRemoveItemRequest)(nil),    // 16: icbt.rpc.v1.EventRemoveItemRequest
	(*EventUpdateItemRequest)(nil),    // 17: icbt.rpc.v1.EventUpdateItemRequest
	(*EventUpdateItemResponse)(nil),   // 18: icbt.rpc.v1.EventUpdateItemResponse
	(*TimestampTZ)(nil),               // 19: icbt.rpc.v1.TimestampTZ
	(*timestamppb.Timestamp)(nil),     // 20: google.protobuf.Timestamp
	(*Earmark)(nil),                   // 21: icbt.rpc.v1.Earmark
	(*PaginationRequest)(nil),         // 22: icbt.rpc.v1.PaginationRequest
	(*PaginationResult)(nil),          // 23: icbt.rpc.v1.PaginationResult
}
var file_icbt_rpc_v1_event_proto_depIdxs = []int32{
	19, // 0: icbt.rpc.v1.Event.when:type_name -> icbt.rpc.v1.TimestampTZ
	20, // 1: icbt.rpc.v1.Event.created:type_name -> google.protobuf.Timestamp
	20, // 2: icbt.rpc.v1.EventItem.created:type_name -> google.protobuf.Timestamp
	19, // 3: icbt.rpc.v1.EventCreateRequest.when:type_name -> icbt.rpc.v1.TimestampTZ
	0,  // 4: icbt.rpc.v1.EventCreateResponse.event:type_name -> icbt.rpc.v1.Event
	19, // 5: icbt.rpc.v1.EventUpdateRequest.when:type_name -> icbt.rpc.v1.TimestampTZ
	0,  // 6: icbt.rpc.v1.EventGetDetailsResponse.event:type_name -> icbt.rpc.v1.Event
	1,  // 7: icbt.rpc.v1.EventGetDetailsResponse.items:type_name -> icbt.rpc.v1.EventItem
	21, // 8: icbt.rpc.v1.EventGetDetailsResponse.earmarks:type_name -> icbt.rpc.v1.Earmark
	22, // 9: icbt.rpc.v1.EventsListRequest.pagination:type_name -> icbt.rpc.v1.PaginationRequest
	0,  // 10: icbt.rpc.v1.EventsListResponse.events:type_name -> icbt.rpc.v1.Event
	23, // 11: icbt.rpc.v1.EventsListResponse.pagination:type_name -> icbt.rpc.v1.PaginationResult
	1,  // 12: icbt.rpc.v1.EventListItemsResponse.items:type_name -> icbt.rpc.v1.EventItem
	23, // 13: icbt.rpc.v1.EventListItemsResponse.pagination:type_name -> icbt.rpc.v1.PaginationResult
	21, // 14: icbt.rpc.v1.EventListEarmarksResponse.earmarks:type_name -> icbt.rpc.v1.Earmark
	23, // 15: icbt.rpc.v1.EventListEarmarksResponse.pagination:type_name -> icbt.rpc.v1.PaginationResult
	1,  // 16: icbt.rpc.v1.EventAddItemResponse.event_item:type_name -> icbt.rpc.v1.EventItem
	1,  // 17: icbt.rpc.v1.EventUpdateItemResponse.event_item:type_name -> icbt.rpc.v1.EventItem
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_icbt_rpc_v1_event_proto_init() }
func file_icbt_rpc_v1_event_proto_init() {
	if File_icbt_rpc_v1_event_proto != nil {
		return
	}
	file_icbt_rpc_v1_constraints_proto_init()
	file_icbt_rpc_v1_earmark_proto_init()
	file_icbt_rpc_v1_pagination_proto_init()
	file_icbt_rpc_v1_timestamptz_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_icbt_rpc_v1_event_proto_rawDesc), len(file_icbt_rpc_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_icbt_rpc_v1_event_proto_goTypes,
		DependencyIndexes: file_icbt_rpc_v1_event_proto_depIdxs,
		MessageInfos:      file_icbt_rpc_v1_event_proto_msgTypes,
	}.Build()
	File_icbt_rpc_v1_event_proto = out.File
	file_icbt_rpc_v1_event_proto_goTypes = nil
	file_icbt_rpc_v1_event_proto_depIdxs = nil
}
