// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: icbt/rpc/v1/service.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_icbt_rpc_v1_service_proto protoreflect.FileDescriptor

const file_icbt_rpc_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19icbt/rpc/v1/service.proto\x12\vicbt.rpc.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a!google/protobuf/go_features.proto\x1a\x19icbt/rpc/v1/earmark.proto\x1a\x17icbt/rpc/v1/event.proto\x1a\x1aicbt/rpc/v1/favorite.proto\x1a\x1eicbt/rpc/v1/notification.proto2\xdd\r\n" +
	"\x0eIcbtRpcService\x12V\n" +
	"\rEarmarkCreate\x12!.icbt.rpc.v1.EarmarkCreateRequest\x1a\".icbt.rpc.v1.EarmarkCreateResponse\x12b\n" +
	"\x11EarmarkGetDetails\x12%.icbt.rpc.v1.EarmarkGetDetailsRequest\x1a&.icbt.rpc.v1.EarmarkGetDetailsResponse\x12J\n" +
	"\rEarmarkRemove\x12!.icbt.rpc.v1.EarmarkRemoveRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\fEarmarksList\x12 .icbt.rpc.v1.EarmarksListRequest\x1a!.icbt.rpc.v1.EarmarksListResponse\x12P\n" +
	"\vEventCreate\x12\x1f.icbt.rpc.v1.EventCreateRequest\x1a .icbt.rpc.v1.EventCreateResponse\x12F\n" +
	"\vEventUpdate\x12\x1f.icbt.rpc.v1.EventUpdateRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\vEventDelete\x12\x1f.icbt.rpc.v1.EventDeleteRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\n" +
	"EventsList\x12\x1e.icbt.rpc.v1.EventsListRequest\x1a\x1f.icbt.rpc.v1.EventsListResponse\x12\\\n" +
	"\x0fEventGetDetails\x12#.icbt.rpc.v1.EventGetDetailsRequest\x1a$.icbt.rpc.v1.EventGetDetailsResponse\x12Y\n" +
	"\x0eEventListItems\x12\".icbt.rpc.v1.EventListItemsRequest\x1a#.icbt.rpc.v1.EventListItemsResponse\x12b\n" +
	"\x11EventListEarmarks\x12%.icbt.rpc.v1.EventListEarmarksRequest\x1a&.icbt.rpc.v1.EventListEarmarksResponse\x12S\n" +
	"\fEventAddItem\x12 .icbt.rpc.v1.EventAddItemRequest\x1a!.icbt.rpc.v1.EventAddItemResponse\x12\\\n" +
	"\x0fEventUpdateItem\x12#.icbt.rpc.v1.EventUpdateItemRequest\x1a$.icbt.rpc.v1.EventUpdateItemResponse\x12N\n" +
	"\x0fEventRemoveItem\x12#.icbt.rpc.v1.EventRemoveItemRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\vFavoriteAdd\x12\x1f.icbt.rpc.v1.FavoriteAddRequest\x1a .icbt.rpc.v1.FavoriteAddResponse\x12L\n" +
	"\x0eFavoriteRemove\x12\".icbt.rpc.v1.FavoriteRemoveRequest\x1a\x16.google.protobuf.Empty\x12e\n" +
	"\x12FavoriteListEvents\x12&.icbt.rpc.v1.FavoriteListEventsRequest\x1a'.icbt.rpc.v1.FavoriteListEventsResponse\x12T\n" +
	"\x12NotificationDelete\x12&.icbt.rpc.v1.NotificationDeleteRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x16NotificationsDeleteAll\x12*.icbt.rpc.v1.NotificationsDeleteAllRequest\x1a\x16.google.protobuf.Empty\x12b\n" +
	"\x11NotificationsList\x12%.icbt.rpc.v1.NotificationsListRequest\x1a&.icbt.rpc.v1.NotificationsListResponseB\xb1\x01\n" +
	"\x0fcom.icbt.rpc.v1B\fServiceProtoP\x01Z8github.com/dropwhile/icanbringthat/rpc/icbt/rpc/v1;rpcv1\xa2\x02\x03IRX\xaa\x02\vIcbt.Rpc.V1\xca\x02\vIcbt\\Rpc\\V1\xe2\x02\x17Icbt\\Rpc\\V1\\GPBMetadata\xea\x02\rIcbt::Rpc::V1\x92\x03\a\xd2>\x02\x10\x03\b\x02b\beditionsp\xe8\a"

var file_icbt_rpc_v1_service_proto_goTypes = []any{
	(*EarmarkCreateRequest)(nil),          // 0: icbt.rpc.v1.EarmarkCreateRequest
	(*EarmarkGetDetailsRequest)(nil),      // 1: icbt.rpc.v1.EarmarkGetDetailsRequest
	(*EarmarkRemoveRequest)(nil),          // 2: icbt.rpc.v1.EarmarkRemoveRequest
	(*EarmarksListRequest)(nil),           // 3: icbt.rpc.v1.EarmarksListRequest
	(*EventCreateRequest)(nil),            // 4: icbt.rpc.v1.EventCreateRequest
	(*EventUpdateRequest)(nil),            // 5: icbt.rpc.v1.EventUpdateRequest
	(*EventDeleteRequest)(nil),            // 6: icbt.rpc.v1.EventDeleteRequest
	(*EventsListRequest)(nil),             // 7: icbt.rpc.v1.EventsListRequest
	(*EventGetDetailsRequest)(nil),        // 8: icbt.rpc.v1.EventGetDetailsRequest
	(*EventListItemsRequest)(nil),         // 9: icbt.rpc.v1.EventListItemsRequest
	(*EventListEarmarksRequest)(nil),      // 10: icbt.rpc.v1.EventListEarmarksRequest
	(*EventAddItemRequest)(nil),           // 11: icbt.rpc.v1.EventAddItemRequest
	(*EventUpdateItemRequest)(nil),        // 12: icbt.rpc.v1.EventUpdateItemRequest
	(*EventRemoveItemRequest)(nil),        // 13: icbt.rpc.v1.EventRemoveItemRequest
	(*FavoriteAddRequest)(nil),            // 14: icbt.rpc.v1.FavoriteAddRequest
	(*FavoriteRemoveRequest)(nil),         // 15: icbt.rpc.v1.FavoriteRemoveRequest
	(*FavoriteListEventsRequest)(nil),     // 16: icbt.rpc.v1.FavoriteListEventsRequest
	(*NotificationDeleteRequest)(nil),     // 17: icbt.rpc.v1.NotificationDeleteRequest
	(*NotificationsDeleteAllRequest)(nil), // 18: icbt.rpc.v1.NotificationsDeleteAllRequest
	(*NotificationsListRequest)(nil),      // 19: icbt.rpc.v1.NotificationsListRequest
	(*EarmarkCreateResponse)(nil),         // 20: icbt.rpc.v1.EarmarkCreateResponse
	(*EarmarkGetDetailsResponse)(nil),     // 21: icbt.rpc.v1.EarmarkGetDetailsResponse
	(*emptypb.Empty)(nil),                 // 22: google.protobuf.Empty
	(*EarmarksListResponse)(nil),          // 23: icbt.rpc.v1.EarmarksListResponse
	(*EventCreateResponse)(nil),           // 24: icbt.rpc.v1.EventCreateResponse
	(*EventsListResponse)(nil),            // 25: icbt.rpc.v1.EventsListResponse
	(*EventGetDetailsResponse)(nil),       // 26: icbt.rpc.v1.EventGetDetailsResponse
	(*EventListItemsResponse)(nil),        // 27: icbt.rpc.v1.EventListItemsResponse
	(*EventListEarmarksResponse)(nil),     // 28: icbt.rpc.v1.EventListEarmarksResponse
	(*EventAddItemResponse)(nil),          // 29: icbt.rpc.v1.EventAddItemResponse
	(*EventUpdateItemResponse)(nil),       // 30: icbt.rpc.v1.EventUpdateItemResponse
	(*FavoriteAddResponse)(nil),           // 31: icbt.rpc.v1.FavoriteAddResponse
	(*FavoriteListEventsResponse)(nil),    // 32: icbt.rpc.v1.FavoriteListEventsResponse
	(*NotificationsListResponse)(nil),     // 33: icbt.rpc.v1.NotificationsListResponse
}
var file_icbt_rpc_v1_service_proto_depIdxs = []int32{
	0,  // 0: icbt.rpc.v1.IcbtRpcService.EarmarkCreate:input_type -> icbt.rpc.v1.EarmarkCreateRequest
	1,  // 1: icbt.rpc.v1.IcbtRpcService.EarmarkGetDetails:input_type -> icbt.rpc.v1.EarmarkGetDetailsRequest
	2,  // 2: icbt.rpc.v1.IcbtRpcService.EarmarkRemove:input_type -> icbt.rpc.v1.EarmarkRemoveRequest
	3,  // 3: icbt.rpc.v1.IcbtRpcService.EarmarksList:input_type -> icbt.rpc.v1.EarmarksListRequest
	4,  // 4: icbt.rpc.v1.IcbtRpcService.EventCreate:input_type -> icbt.rpc.v1.EventCreateRequest
	5,  // 5: icbt.rpc.v1.IcbtRpcService.EventUpdate:input_type -> icbt.rpc.v1.EventUpdateRequest
	6,  // 6: icbt.rpc.v1.IcbtRpcService.EventDelete:input_type -> icbt.rpc.v1.EventDeleteRequest
	7,  // 7: icbt.rpc.v1.IcbtRpcService.EventsList:input_type -> icbt.rpc.v1.EventsListRequest
	8,  // 8: icbt.rpc.v1.IcbtRpcService.EventGetDetails:input_type -> icbt.rpc.v1.EventGetDetailsRequest
	9,  // 9: icbt.rpc.v1.IcbtRpcService.EventListItems:input_type -> icbt.rpc.v1.EventListItemsRequest
	10, // 10: icbt.rpc.v1.IcbtRpcService.EventListEarmarks:input_type -> icbt.rpc.v1.EventListEarmarksRequest
	11, // 11: icbt.rpc.v1.IcbtRpcService.EventAddItem:input_type -> icbt.rpc.v1.EventAddItemRequest
	12, // 12: icbt.rpc.v1.IcbtRpcService.EventUpdateItem:input_type -> icbt.rpc.v1.EventUpdateItemRequest
	13, // 13: icbt.rpc.v1.IcbtRpcService.EventRemoveItem:input_type -> icbt.rpc.v1.EventRemoveItemRequest
	14, // 14: icbt.rpc.v1.IcbtRpcService.FavoriteAdd:input_type -> icbt.rpc.v1.FavoriteAddRequest
	15, // 15: icbt.rpc.v1.IcbtRpcService.FavoriteRemove:input_type -> icbt.rpc.v1.FavoriteRemoveRequest
	16, // 16: icbt.rpc.v1.IcbtRpcService.FavoriteListEvents:input_type -> icbt.rpc.v1.FavoriteListEventsRequest
	17, // 17: icbt.rpc.v1.IcbtRpcService.NotificationDelete:input_type -> icbt.rpc.v1.NotificationDeleteRequest
	18, // 18: icbt.rpc.v1.IcbtRpcService.NotificationsDeleteAll:input_type -> icbt.rpc.v1.NotificationsDeleteAllRequest
	19, // 19: icbt.rpc.v1.IcbtRpcService.NotificationsList:input_type -> icbt.rpc.v1.NotificationsListRequest
	20, // 20: icbt.rpc.v1.IcbtRpcService.EarmarkCreate:output_type -> icbt.rpc.v1.EarmarkCreateResponse
	21, // 21: icbt.rpc.v1.IcbtRpcService.EarmarkGetDetails:output_type -> icbt.rpc.v1.EarmarkGetDetailsResponse
	22, // 22: icbt.rpc.v1.IcbtRpcService.EarmarkRemove:output_type -> google.protobuf.Empty
	23, // 23: icbt.rpc.v1.IcbtRpcService.EarmarksList:output_type -> icbt.rpc.v1.EarmarksListResponse
	24, // 24: icbt.rpc.v1.IcbtRpcService.EventCreate:output_type -> icbt.rpc.v1.EventCreateResponse
	22, // 25: icbt.rpc.v1.IcbtRpcService.EventUpdate:output_type -> google.protobuf.Empty
	22, // 26: icbt.rpc.v1.IcbtRpcService.EventDelete:output_type -> google.protobuf.Empty
	25, // 27: icbt.rpc.v1.IcbtRpcService.EventsList:output_type -> icbt.rpc.v1.EventsListResponse
	26, // 28: icbt.rpc.v1.IcbtRpcService.EventGetDetails:output_type -> icbt.rpc.v1.EventGetDetailsResponse
	27, // 29: icbt.rpc.v1.IcbtRpcService.EventListItems:output_type -> icbt.rpc.v1.EventListItemsResponse
	28, // 30: icbt.rpc.v1.IcbtRpcService.EventListEarmarks:output_type -> icbt.rpc.v1.EventListEarmarksResponse
	29, // 31: icbt.rpc.v1.IcbtRpcService.EventAddItem:output_type -> icbt.rpc.v1.EventAddItemResponse
	30, // 32: icbt.rpc.v1.IcbtRpcService.EventUpdateItem:output_type -> icbt.rpc.v1.EventUpdateItemResponse
	22, // 33: icbt.rpc.v1.IcbtRpcService.EventRemoveItem:output_type -> google.protobuf.Empty
	31, // 34: icbt.rpc.v1.IcbtRpcService.FavoriteAdd:output_type -> icbt.rpc.v1.FavoriteAddResponse
	22, // 35: icbt.rpc.v1.IcbtRpcService.FavoriteRemove:output_type -> google.protobuf.Empty
	32, // 36: icbt.rpc.v1.IcbtRpcService.FavoriteListEvents:output_type -> icbt.rpc.v1.FavoriteListEventsResponse
	22, // 37: icbt.rpc.v1.IcbtRpcService.NotificationDelete:output_type -> google.protobuf.Empty
	22, // 38: icbt.rpc.v1.IcbtRpcService.NotificationsDeleteAll:output_type -> google.protobuf.Empty
	33, // 39: icbt.rpc.v1.IcbtRpcService.NotificationsList:output_type -> icbt.rpc.v1.NotificationsListResponse
	20, // [20:40] is the sub-list for method output_type
	0,  // [0:20] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_icbt_rpc_v1_service_proto_init() }
func file_icbt_rpc_v1_service_proto_init() {
	if File_icbt_rpc_v1_service_proto != nil {
		return
	}
	file_icbt_rpc_v1_earmark_proto_init()
	file_icbt_rpc_v1_event_proto_init()
	file_icbt_rpc_v1_favorite_proto_init()
	file_icbt_rpc_v1_notification_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_icbt_rpc_v1_service_proto_rawDesc), len(file_icbt_rpc_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_icbt_rpc_v1_service_proto_goTypes,
		DependencyIndexes: file_icbt_rpc_v1_service_proto_depIdxs,
	}.Build()
	File_icbt_rpc_v1_service_proto = out.File
	file_icbt_rpc_v1_service_proto_goTypes = nil
	file_icbt_rpc_v1_service_proto_depIdxs = nil
}
