// Code generated by github.com/reedom/convergen
// DO NOT EDIT.

package dto

import (
	"github.com/dropwhile/icbt/internal/app/model"
	"github.com/dropwhile/icbt/rpc"
)

func ToPbNotification(src *model.Notification) (dst *rpc.Notification) {
	dst = &rpc.Notification{}
	dst.RefId = src.RefID.String()
	dst.Message = src.Message
	dst.Created = TimeToTimestamp(src.Created)

	return
}
