services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./database/init/load-extensions.sql:/docker-entrypoint-initdb.d/load-extensions.sql

  app:
    image: "icbt:latest"
    restart: always
    ports:
      - "8000:8000"
    environment:
      #TPL_DIR: "embed"
      #STATIC_DIR: "embed"
      LOG_LEVEL: "debug"
      LOG_FORMAT: "plain"
      PRODUCTION: "true"
      DB_DSN: "postgres://${PGUSER}:${PGPASSWORD}@db/${PGDATABASE}?sslmode=disable"
      CSRF_KEY: ${CSRF_KEY}
      SMTP_HOSTNAME: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "postgres://${PGUSER}:${PGPASSWORD}@db/${PGDATABASE}?sslmode=disable"
      GOOSE_MIGRATION_DIR: database/migrations

