// Code generated by refidgen. DO NOT EDIT.

package modelx

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagValVerifyRefID = 6

type VerifyRefID struct {
	refid.RefID
}

func (r *VerifyRefID) checkResult(err error) error {
	if err != nil {
		return err
	}
	if !r.RefID.HasTag(tagValVerifyRefID) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *VerifyRefID) Scan(src interface{}) error {
	err := r.RefID.Scan(src)
	return r.checkResult(err)
}

func (r *VerifyRefID) UnmarshalJSON(b []byte) error {
	err := r.RefID.UnmarshalJSON(b)
	return r.checkResult(err)
}

func (r *VerifyRefID) UnmarshalBinary(b []byte) error {
	err := r.RefID.UnmarshalJSON(b)
	return r.checkResult(err)
}

func NewVerifyRefID() (VerifyRefID, error) {
	v, err := refid.NewTagged(tagValVerifyRefID)
	return VerifyRefID{v}, err
}

func ParseVerifyRefID(s string) (VerifyRefID, error) {
	v, err := refid.ParseWithRequire(s, refid.HasTag(tagValVerifyRefID))
	return VerifyRefID{v}, err
}

func ParseVerifyRefIDWithRequire(s string, reqs ...refid.Requirement) (VerifyRefID, error) {
	reqs = append(reqs, refid.HasTag(tagValVerifyRefID))
	v, err := refid.ParseWithRequire(s, reqs...)
	return VerifyRefID{v}, err
}

type NullVerifyRefID struct {
	refid.NullRefID
}

func (u *NullVerifyRefID) checkResult(err error) error {
	if err != nil {
		return err
	}
	n := u.NullRefID
	if n.Valid && !n.RefID.HasTag(tagValVerifyRefID) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}


func (u *NullVerifyRefID) Scan(src interface{}) error {
	err := u.NullRefID.Scan(src)
	return u.checkResult(err)
}

func (u *NullVerifyRefID) UnmarshalJSON(b []byte) error {
	err := u.NullRefID.UnmarshalJSON(b)
	return u.checkResult(err)
}

type VerifyRefIDMatcher struct{}

func (a VerifyRefIDMatcher) Match(v interface{}) bool {
	var r refid.RefID
	var err error
	switch x := v.(type) {
	case VerifyRefID:
		r = x.RefID
	case *VerifyRefID:
		r = x.RefID
	case string:
		r, err = refid.Parse(x)
	case []byte:
		r, err = refid.FromBytes(x)
	default:
		return false
	}
	if err != nil {
		return false
	}
	return r.HasTag(tagValVerifyRefID)
}
