// Code generated by "stringer -type=Code"; DO NOT EDIT.

package errs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoError-0]
	_ = x[Canceled-1]
	_ = x[Unknown-2]
	_ = x[InvalidArgument-3]
	_ = x[DeadlineExceeded-4]
	_ = x[NotFound-5]
	_ = x[AlreadyExists-6]
	_ = x[PermissionDenied-7]
	_ = x[ResourceExhausted-8]
	_ = x[FailedPrecondition-9]
	_ = x[Aborted-10]
	_ = x[OutOfRange-11]
	_ = x[Unimplemented-12]
	_ = x[Internal-13]
	_ = x[Unavailable-14]
	_ = x[DataLoss-15]
	_ = x[Unauthenticated-16]
}

const _Code_name = "NoErrorCanceledUnknownInvalidArgumentDeadlineExceededNotFoundAlreadyExistsPermissionDeniedResourceExhaustedFailedPreconditionAbortedOutOfRangeUnimplementedInternalUnavailableDataLossUnauthenticated"

var _Code_index = [...]uint8{0, 7, 15, 22, 37, 53, 61, 74, 90, 107, 125, 132, 142, 155, 163, 174, 182, 197}

func (i Code) String() string {
	if i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
