#!/bin/sh

set -e

MIG_DIR="$(dirname "$(dirname "${0}")")/migrations"

if [ -z "$DB_DSN" ]; then
    echo "DB_DSN is not specified. Giving up!"
    exit 1
fi

case $1 in
    up)
        exec migrate \
            -path "${MIG_DIR}" \
            -database "${DB_DSN}" \
        up
        ;;
    new)
        if [ -z "$2" ]; then
            echo "ERROR: No name provided for migration"
            exit 1
        fi
        exec migrate create \
            -ext sql \
            -dir "${MIG_DIR}" \
            -seq "${2}"
        ;;
    *)
        exec migrate -path "${MIG_DIR}" -database "${DB_DSN}" "$@"
        ;;
esac

