// Code generated by refidgen. DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagValEventItemRefID = 3

type EventItemRefID struct {
	refid.RefID
}

func (r *EventItemRefID) checkResult(err error) error {
	if err != nil {
		return err
	}
	if !r.RefID.HasTag(tagValEventItemRefID) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *EventItemRefID) Scan(src interface{}) error {
	err := r.RefID.Scan(src)
	return r.checkResult(err)
}

func (r *EventItemRefID) UnmarshalJSON(b []byte) error {
	err := r.RefID.UnmarshalJSON(b)
	return r.checkResult(err)
}

func (r *EventItemRefID) UnmarshalBinary(b []byte) error {
	err := r.RefID.UnmarshalJSON(b)
	return r.checkResult(err)
}

func NewEventItemRefID() (EventItemRefID, error) {
	v, err := refid.NewTagged(tagValEventItemRefID)
	return EventItemRefID{v}, err
}

func ParseEventItemRefID(s string) (EventItemRefID, error) {
	v, err := refid.ParseWithRequire(s, refid.HasTag(tagValEventItemRefID))
	return EventItemRefID{v}, err
}

func ParseEventItemRefIDWithRequire(s string, reqs ...refid.Requirement) (EventItemRefID, error) {
	reqs = append(reqs, refid.HasTag(tagValEventItemRefID))
	v, err := refid.ParseWithRequire(s, reqs...)
	return EventItemRefID{v}, err
}

type NullEventItemRefID struct {
	refid.NullRefID
}

func (u *NullEventItemRefID) checkResult(err error) error {
	if err != nil {
		return err
	}
	n := u.NullRefID
	if n.Valid && !n.RefID.HasTag(tagValEventItemRefID) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}


func (u *NullEventItemRefID) Scan(src interface{}) error {
	err := u.NullRefID.Scan(src)
	return u.checkResult(err)
}

func (u *NullEventItemRefID) UnmarshalJSON(b []byte) error {
	err := u.NullRefID.UnmarshalJSON(b)
	return u.checkResult(err)
}

type EventItemRefIDMatcher struct{}

func (a EventItemRefIDMatcher) Match(v interface{}) bool {
	var r refid.RefID
	var err error
	switch x := v.(type) {
	case EventItemRefID:
		r = x.RefID
	case *EventItemRefID:
		r = x.RefID
	case string:
		r, err = refid.Parse(x)
	case []byte:
		r, err = refid.FromBytes(x)
	default:
		return false
	}
	if err != nil {
		return false
	}
	return r.HasTag(tagValEventItemRefID)
}
