// Code generated by refidgen. DO NOT EDIT.
// generated from: notification.go

package model

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagValNotificationRefID = 8

type NotificationRefID struct {
	refid.ID
}

func (r *NotificationRefID) checkResult(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagValNotificationRefID) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *NotificationRefID) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.checkResult(err)
}

func (r *NotificationRefID) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.checkResult(err)
}

func (r *NotificationRefID) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.checkResult(err)
}

func NewNotificationRefID() (NotificationRefID, error) {
	v, err := refid.NewTagged(tagValNotificationRefID)
	return NotificationRefID{v}, err
}

func ParseNotificationRefID(s string) (NotificationRefID, error) {
	v, err := refid.ParseWithRequire(s, refid.HasTag(tagValNotificationRefID))
	return NotificationRefID{v}, err
}

func ParseNotificationRefIDWithRequire(s string, reqs ...refid.Requirement) (NotificationRefID, error) {
	reqs = append(reqs, refid.HasTag(tagValNotificationRefID))
	v, err := refid.ParseWithRequire(s, reqs...)
	return NotificationRefID{v}, err
}

func NotificationRefIDFromBytes(input []byte) (NotificationRefID, error) {
	var r NotificationRefID
	err := r.UnmarshalBinary(input)
	return r, err
}

type NullNotificationRefID struct {
	refid.NullID
}

func (u *NullNotificationRefID) checkResult(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagValNotificationRefID) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}


func (u *NullNotificationRefID) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.checkResult(err)
}

func (u *NullNotificationRefID) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.checkResult(err)
}

type NotificationRefIDMatcher struct{}

func (a NotificationRefIDMatcher) Match(v interface{}) bool {
	var r refid.ID
	var err error
	switch x := v.(type) {
	case NotificationRefID:
		r = x.ID
	case *NotificationRefID:
		r = x.ID
	case string:
		r, err = refid.Parse(x)
	case []byte:
		r, err = refid.FromBytes(x)
	default:
		return false
	}
	if err != nil {
		return false
	}
	return r.HasTag(tagValNotificationRefID)
}
