// Code generated by refidgen. DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagValUserVerifyRefID = 6

type UserVerifyRefID struct {
	refid.RefID
}

func (r *UserVerifyRefID) checkResult(err error) error {
	if err != nil {
		return err
	}
	if !r.RefID.HasTag(tagValUserVerifyRefID) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *UserVerifyRefID) Scan(src interface{}) error {
	err := r.RefID.Scan(src)
	return r.checkResult(err)
}

func (r *UserVerifyRefID) UnmarshalJSON(b []byte) error {
	err := r.RefID.UnmarshalJSON(b)
	return r.checkResult(err)
}

func (r *UserVerifyRefID) UnmarshalBinary(b []byte) error {
	err := r.RefID.UnmarshalJSON(b)
	return r.checkResult(err)
}

func NewUserVerifyRefID() (UserVerifyRefID, error) {
	v, err := refid.NewTagged(tagValUserVerifyRefID)
	return UserVerifyRefID{v}, err
}

func ParseUserVerifyRefID(s string) (UserVerifyRefID, error) {
	v, err := refid.ParseWithRequire(s, refid.HasTag(tagValUserVerifyRefID))
	return UserVerifyRefID{v}, err
}

func ParseUserVerifyRefIDWithRequire(s string, reqs ...refid.Requirement) (UserVerifyRefID, error) {
	reqs = append(reqs, refid.HasTag(tagValUserVerifyRefID))
	v, err := refid.ParseWithRequire(s, reqs...)
	return UserVerifyRefID{v}, err
}

type NullUserVerifyRefID struct {
	refid.NullRefID
}

func (u *NullUserVerifyRefID) checkResult(err error) error {
	if err != nil {
		return err
	}
	n := u.NullRefID
	if n.Valid && !n.RefID.HasTag(tagValUserVerifyRefID) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}


func (u *NullUserVerifyRefID) Scan(src interface{}) error {
	err := u.NullRefID.Scan(src)
	return u.checkResult(err)
}

func (u *NullUserVerifyRefID) UnmarshalJSON(b []byte) error {
	err := u.NullRefID.UnmarshalJSON(b)
	return u.checkResult(err)
}

type UserVerifyRefIDMatcher struct{}

func (a UserVerifyRefIDMatcher) Match(v interface{}) bool {
	var r refid.RefID
	var err error
	switch x := v.(type) {
	case UserVerifyRefID:
		r = x.RefID
	case *UserVerifyRefID:
		r = x.RefID
	case string:
		r, err = refid.Parse(x)
	case []byte:
		r, err = refid.FromBytes(x)
	default:
		return false
	}
	if err != nil {
		return false
	}
	return r.HasTag(tagValUserVerifyRefID)
}
