// Code generated by refidgen. DO NOT EDIT.
// generated from: user_pw_reset.go

package model

import (
	"fmt"

	"github.com/dropwhile/refid"
)

const tagValUserPWResetRefID = 5

type UserPWResetRefID struct {
	refid.ID
}

func (r *UserPWResetRefID) checkResult(err error) error {
	if err != nil {
		return err
	}
	if !r.ID.HasTag(tagValUserPWResetRefID) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}

func (r *UserPWResetRefID) Scan(src interface{}) error {
	err := r.ID.Scan(src)
	return r.checkResult(err)
}

func (r *UserPWResetRefID) UnmarshalJSON(b []byte) error {
	err := r.ID.UnmarshalJSON(b)
	return r.checkResult(err)
}

func (r *UserPWResetRefID) UnmarshalBinary(b []byte) error {
	err := r.ID.UnmarshalBinary(b)
	return r.checkResult(err)
}

func NewUserPWResetRefID() (UserPWResetRefID, error) {
	v, err := refid.NewTagged(tagValUserPWResetRefID)
	return UserPWResetRefID{v}, err
}

func ParseUserPWResetRefID(s string) (UserPWResetRefID, error) {
	v, err := refid.ParseWithRequire(s, refid.HasTag(tagValUserPWResetRefID))
	return UserPWResetRefID{v}, err
}

func ParseUserPWResetRefIDWithRequire(s string, reqs ...refid.Requirement) (UserPWResetRefID, error) {
	reqs = append(reqs, refid.HasTag(tagValUserPWResetRefID))
	v, err := refid.ParseWithRequire(s, reqs...)
	return UserPWResetRefID{v}, err
}

func UserPWResetRefIDFromBytes(input []byte) (UserPWResetRefID, error) {
	var r UserPWResetRefID
	err := r.UnmarshalBinary(input)
	return r, err
}

type NullUserPWResetRefID struct {
	refid.NullID
}

func (u *NullUserPWResetRefID) checkResult(err error) error {
	if err != nil {
		return err
	}
	n := u.NullID
	if n.Valid && !n.ID.HasTag(tagValUserPWResetRefID) {
		return fmt.Errorf("wrong refid type")
	}
	return nil
}


func (u *NullUserPWResetRefID) Scan(src interface{}) error {
	err := u.NullID.Scan(src)
	return u.checkResult(err)
}

func (u *NullUserPWResetRefID) UnmarshalJSON(b []byte) error {
	err := u.NullID.UnmarshalJSON(b)
	return u.checkResult(err)
}

type UserPWResetRefIDMatcher struct{}

func (a UserPWResetRefIDMatcher) Match(v interface{}) bool {
	var r refid.ID
	var err error
	switch x := v.(type) {
	case UserPWResetRefID:
		r = x.ID
	case *UserPWResetRefID:
		r = x.ID
	case string:
		r, err = refid.Parse(x)
	case []byte:
		r, err = refid.FromBytes(x)
	default:
		return false
	}
	if err != nil {
		return false
	}
	return r.HasTag(tagValUserPWResetRefID)
}
